export const CREATE_ELEMENT = 'CREATE_ELEMENT';
export const TOGGLE_ELEMENT = 'TOGGLE_ELEMENT';
export const UPDATE_ELEMENTS = 'UPDATE_ELEMENTS';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const INSERT_ELEMENT = 'INSERT_ELEMENT';
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT';

export const CREATE_FORM = 'CREATE_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const DELETE_FORM = 'DELETE_FORM';
export const TOGGLE_FORM = 'TOGGLE_FORM';
